development:
  adapter: postgresql
  encoding: unicode
  database: read_dev
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: read_test
  pool: 5
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: read_prod
  pool: 5
  username: postgres
  password: postgres
